spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barber_shop_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true